#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build.py -- build the website of Assoc. Prof. Phuong Luu Vo.

WHAT IT DOES
    1. Collects every ``www/*.jemdoc`` file (except the shared ``menu.jemdoc``).
    2. Copies them plus ``www/mysite.conf`` into a temporary staging folder,
       normalising line endings to LF. (jemdoc is sensitive to Windows CRLF
       line endings, so this step makes the build work the same everywhere.)
    3. Runs ``tools/jemdoc`` on every page, which produces ``*.html``.
    4. Copies the generated HTML plus the static folders
       (``css/``, ``files/``, ``images/``) and ``CNAME`` into the output folder.
    5. Regenerates ``files/publications.bib`` from the BibTeX blocks found in
       ``www/publications.jemdoc``, so the downloadable .bib file can never go
       out of sync with the page.

USAGE
    python build.py                  build into the repository root (default)
    python build.py --out _site      build into the folder ``_site``
    python build.py --serve          build, then open a local preview server
    python build.py --clean          delete the generated HTML files
    python build.py --no-bib         skip regenerating files/publications.bib

Everything you normally edit lives in ``www/``. See GUIDE.md.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "www")
TOOLS = os.path.join(ROOT, "tools")
JEMDOC = os.path.join(TOOLS, "jemdoc")
CONF = "mysite.conf"

#: jemdoc files in www/ that are NOT standalone pages.
NOT_A_PAGE = {"menu.jemdoc", CONF}

#: Folders in www/ that are copied verbatim to the output folder.
ASSET_DIRS = ("css", "files", "images")

#: BibTeX blocks are harvested from this page.
BIB_SOURCE = "publications.jemdoc"
BIB_OUTPUT = os.path.join("files", "publications.bib")


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #

def read_text_lf(path: str) -> str:
    """Read a file and return its contents with LF line endings."""
    with open(path, "r", encoding="utf-8", newline="") as handle:
        return handle.read().replace("\r\n", "\n").replace("\r", "\n")


def find_pages() -> list[str]:
    """Return the names of all .jemdoc pages, alphabetically."""
    pages = [
        name
        for name in sorted(os.listdir(SRC))
        if name.endswith(".jemdoc") and name not in NOT_A_PAGE
    ]
    if not pages:
        sys.exit("error: no .jemdoc pages found in %s" % SRC)
    return pages


def extract_bibtex(text: str) -> list[str]:
    """Pull every jemdoc code block whose language is ``bibtex`` out of *text*."""
    entries: list[str] = []
    lines = text.split("\n")
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.lstrip()
        # A code block starts with a line of tildes, followed by {title}{language}.
        if stripped.startswith("~~~") or (
            stripped.startswith("~") and set(stripped) == {"~"}
        ):
            header = lines[index + 1] if index + 1 < len(lines) else ""
            if header.strip().startswith("{"):
                groups = re.findall(r"(?<!\\){(.*?)(?<!\\)}", header)
                language = groups[1].strip().lower() if len(groups) >= 2 else ""
                body = []
                cursor = index + 2
                while cursor < len(lines) and not lines[cursor].startswith("~"):
                    body.append(lines[cursor])
                    cursor += 1
                if language == "bibtex":
                    entries.append("\n".join(body).strip("\n"))
                index = cursor
                continue
            index += 1
            continue
        index += 1
    return entries


def write_publications_bib(source_file: str, destination: str) -> int:
    """Rebuild the downloadable .bib file from the publications page."""
    if not os.path.isfile(source_file):
        return 0
    entries = extract_bibtex(read_text_lf(source_file))
    if not entries:
        return 0
    header = (
        "% BibTeX export generated automatically by build.py.\n"
        "% Do not edit this file by hand -- edit www/publications.jemdoc instead,\n"
        "% then run:  python build.py\n\n"
    )
    os.makedirs(os.path.dirname(destination), exist_ok=True)
    with open(destination, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header + "\n\n".join(entries) + "\n")
    return len(entries)


# --------------------------------------------------------------------------- #
# build steps
# --------------------------------------------------------------------------- #

def run_jemdoc(staging: str, pages: list[str]) -> None:
    """Run jemdoc inside *staging* to turn every page into HTML."""
    command = [
        sys.executable,
        "-W", "ignore",          # silence harmless SyntaxWarnings from jemdoc
        JEMDOC,
        "-c", CONF,
    ] + pages
    result = subprocess.run(command, cwd=staging, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        sys.exit("error: jemdoc failed (exit code %d)" % result.returncode)
    if result.stderr.strip():
        # jemdoc warnings are usually interesting enough to show.
        for line in result.stderr.strip().splitlines():
            if "SyntaxWarning" not in line:
                print("jemdoc: " + line)


def stage_sources(staging: str, pages: list[str]) -> None:
    """Copy the .jemdoc sources (and the menu) into *staging* with LF endings."""
    names = sorted(
        name for name in os.listdir(SRC) if name.endswith(".jemdoc")
    ) + [CONF]
    for name in names:
        source = os.path.join(SRC, name)
        if not os.path.isfile(source):
            continue
        text = read_text_lf(source)
        with open(os.path.join(staging, name), "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)


def copy_assets(outdir: str) -> list[str]:
    """Copy css/, files/ and images/ from www/ to the output folder."""
    copied = []
    for name in ASSET_DIRS:
        source = os.path.join(SRC, name)
        if not os.path.isdir(source):
            continue
        target = os.path.join(outdir, name)
        shutil.copytree(source, target, dirs_exist_ok=True)
        copied.append(name + "/")
    return copied


def clean(outdir: str, pages: list[str]) -> None:
    """Remove the generated HTML files."""
    removed = 0
    for name in pages:
        html = os.path.join(outdir, name[:-len(".jemdoc")] + ".html")
        if os.path.isfile(html):
            os.remove(html)
            removed += 1
    print("clean: removed %d generated HTML file(s) from %s" % (removed, outdir))


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #

def build(outdir: str, make_bib: bool = True) -> None:
    outdir = os.path.abspath(outdir)
    os.makedirs(outdir, exist_ok=True)
    pages = find_pages()

    staging = tempfile.mkdtemp(prefix="jemdoc-build-")
    try:
        stage_sources(staging, pages)
        run_jemdoc(staging, pages)

        written = []
        for name in pages:
            html = name[:-len(".jemdoc")] + ".html"
            shutil.copyfile(os.path.join(staging, html), os.path.join(outdir, html))
            written.append(html)
    finally:
        shutil.rmtree(staging, ignore_errors=True)

    assets = copy_assets(outdir)

    # GitHub Pages must not run Jekyll over the output.
    with open(os.path.join(outdir, ".nojekyll"), "w", encoding="utf-8") as handle:
        handle.write("")

    for extra in ("CNAME",):
        source = os.path.join(ROOT, extra)
        destination = os.path.join(outdir, extra)
        if os.path.isfile(source) and os.path.abspath(source) != os.path.abspath(destination):
            shutil.copyfile(source, destination)

    bib_count = 0
    if make_bib:
        bib_count = write_publications_bib(
            os.path.join(SRC, BIB_SOURCE), os.path.join(outdir, BIB_OUTPUT)
        )

    print("Build finished.")
    print("  output folder : %s" % outdir)
    print("  pages written : %d" % len(written))
    for name in written:
        print("                  %s" % name)
    if assets:
        print("  assets copied : %s" % ", ".join(assets))
    if make_bib:
        if bib_count:
            print("  bibtex export : %s (%d entries)" % (BIB_OUTPUT, bib_count))
        else:
            print("  bibtex export : %s (no bibtex blocks found)" % BIB_OUTPUT)


def serve(outdir: str) -> None:
    """Build and then serve the site on http://localhost:8000."""
    import functools
    import http.server
    import socketserver
    import threading
    import webbrowser

    build(outdir)
    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=outdir)
    with socketserver.TCPServer(("127.0.0.1", 8000), handler) as httpd:
        url = "http://localhost:8000/"
        print("\nPreview server running at %s  (press Ctrl+C to stop)" % url)
        threading.Timer(0.8, lambda: webbrowser.open(url)).start()
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nPreview server stopped.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build the website from the .jemdoc sources in www/."
    )
    parser.add_argument(
        "-o", "--out",
        default=ROOT,
        help="output folder (default: the repository root)",
    )
    parser.add_argument(
        "--serve", action="store_true",
        help="build, then serve the site locally on port 8000",
    )
    parser.add_argument(
        "--clean", action="store_true",
        help="delete the generated HTML files instead of building",
    )
    parser.add_argument(
        "--no-bib", action="store_true",
        help="do not regenerate files/publications.bib",
    )
    args = parser.parse_args()

    if not os.path.isfile(JEMDOC):
        sys.exit("error: %s not found. Are you running build.py from the "
                 "repository root?" % JEMDOC)

    if args.clean:
        clean(os.path.abspath(args.out), find_pages())
        return

    if args.serve:
        serve(args.out)
        return

    build(args.out, make_bib=not args.no_bib)


if __name__ == "__main__":
    main()
