#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_publications.py -- write the Publications page from www/data/publications.bib.

WHY
    The page used to be refreshed over the network from an ORCID record. That
    kept it complete, but it also meant the page could not be corrected by hand:
    the next run overwrote whatever was fixed, and a work entered in ORCID with
    the wrong year came back wrong. The list lives in BibTeX now -- the format an
    academic already keeps, and the one a publisher hands out -- so adding a
    paper is pasting a few lines into a file, and this script renders them.

WHAT IT DOES
    Reads www/data/publications.bib and writes www/profile/publications.jemdoc,
    as **jemdoc**: a section per kind of work and one bullet per reference. The
    page is then an ordinary page of the site, styled by the stylesheet like
    every other list on it, and readable as a source.

    The kind of work comes from the entry type:

        @article       journal article
        @inproceedings conference paper        (@conference as well)
        @incollection  book chapter            (@inbook as well)

    and adding ``kind = {national}`` to a journal or conference entry lists it
    under the national sections at the end instead of the international ones.

    A reference is printed as its authors, the title in quotes, the venue in
    italics, and the volume, pages and year. There are **no links**: a DOI is
    data, not something the page needs to carry, and a bare URL in jemdoc prose
    is a trap -- the "/" in it pairs with the "/" of the italics that follow and
    silently italicises the rest of the page.

WHAT IT DOES NOT DO
    It fetches nothing and touches no other page. The pages that are not lists of
    references -- Supervision, Projects, Patents, Awards -- are hand-written,
    because their entries are not citations.

USAGE
    python tools/build_publications.py            # write the page
    python tools/build_publications.py --check    # say whether it is up to date
    python tools/build_publications.py --dry-run  # print the page, write nothing

    Standard library only, like build.py. The page it writes is committed, so the
    site still builds with no BibTeX file and no network.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "www", "data", "publications.bib")
OUTPUT = os.path.join(ROOT, "www", "profile", "publications.jemdoc")

#: The sections of the page, in order, and the entry types that feed each one.
#: ``national`` marks the two sections fed by entries carrying kind = {national}.
SECTIONS = (
    ("Journal Articles", "article", False),
    ("Conference Papers", ("inproceedings", "conference"), False),
    ("Book Chapters", ("incollection", "inbook"), False),
    ("National Journal Articles", "article", True),
    ("National Conference Papers", ("inproceedings", "conference"), True),
)

MONTHS = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
    "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12,
}

#: The owner, as the family and given names appear in a BibTeX name. The family
#: name is compared without case, hyphens or spaces, and the given name has to
#: look like hers, so a co-author called Vo does not go bold.
OWNER_FAMILY = "vo"
OWNER_GIVEN = re.compile(r"\bphuong\b|\bp\.?\s*l\.?\b", re.I)

HEADER = """# jemdoc: menu{menu.jemdoc}{publications.html}, title{Publications}, notime
# GENERATED by tools/build_publications.py -- do not edit this file by hand.
# The list is www/data/publications.bib; edit that and run:
#     python tools/build_publications.py        (or: make publications)
"""

#: How the references are wrapped. jemdoc keeps a bullet together while its
#: continuation lines are indented, so a wrapped reference stays one entry.
WIDTH = 96


# --------------------------------------------------------------------------- #
# BibTeX
# --------------------------------------------------------------------------- #

def strip_comments(text):
    """Drop %-comments; keep the entries."""
    return "\n".join(line for line in text.splitlines()
                     if not line.lstrip().startswith("%"))


def parse_entries(text):
    """The file as a list of (type, fields); fields keep their braces off.

    The body of an entry is found by counting braces rather than by matching a
    pattern, so an entry may be written on one line or spread over ten, and a
    brace inside a title is part of the title rather than a parser's problem.
    """
    text = strip_comments(text)
    fields = r"([A-Za-z]+)\s*=\s*\{((?:[^{}]|\{[^{}]*\})*)\}"
    entries = []
    for match in re.finditer(r"@([A-Za-z]+)\s*\{\s*([^,\s]*)", text):
        kind, key = match.group(1).lower(), match.group(2)
        if kind in ("string", "preamble", "comment"):
            continue
        depth, index = 1, match.end()
        while index < len(text) and depth:
            if text[index] == "{":
                depth += 1
            elif text[index] == "}":
                depth -= 1
            index += 1
        if depth:
            raise SystemExit("an entry is not closed: %s" % key)
        body = text[match.end():index - 1]
        values = {}
        for name, value in re.findall(fields, body, re.S):
            values[name.lower()] = re.sub(r"\s+", " ", value).strip()
        values["key"] = key
        entries.append((kind, values))
    return entries


def entry_date(fields):
    """(year, month) as integers, either possibly 0 when the source has neither."""
    year = month = 0
    date = fields.get("date", "")
    found = re.match(r"(\d{4})(?:-(\d{1,2}))?", date)
    if found:
        year = int(found.group(1))
        if found.group(2):
            month = int(found.group(2))
    if not year:
        found = re.search(r"\d{4}", fields.get("year", ""))
        year = int(found.group(0)) if found else 0
    if not month:
        raw = fields.get("month", "").strip().lower()
        if raw[:3] in MONTHS:
            month = MONTHS[raw[:3]]
        elif raw.isdigit():
            month = int(raw)
    return year, month


# --------------------------------------------------------------------------- #
# names
# --------------------------------------------------------------------------- #

def split_names(value):
    """A BibTeX name list as [(family, given), ...]."""
    names = []
    for piece in re.split(r"\s+and\s+", value.strip().rstrip(".")):
        piece = re.sub(r"\s+", " ", piece).strip()
        if not piece:
            continue
        if "," in piece:
            family, given = piece.split(",", 1)
        else:
            words = piece.split()
            family, given = words[-1], " ".join(words[:-1])
        names.append((family.strip(), given.strip()))
    return names


def is_owner(family, given):
    """True for the site owner's own name, in any of the spellings publishers use.

    "Vo, Phuong L.", "Vo-Thi-Luu, Phuong" and "Vo, Phuong Luu" are the same
    person; "Vo, Minh" is not, which is why the given name has to match too.
    """
    flat = re.sub(r"[^a-z]", "", family.lower())
    if flat != OWNER_FAMILY and not flat.startswith(OWNER_FAMILY + "thi"):
        return False
    return bool(OWNER_GIVEN.search(given))


def render_authors(value):
    """The author list as it is printed: given name first, the owner in bold."""
    parts = []
    for family, given in split_names(value):
        name = escape(("%s %s" % (given, family)).strip())
        if is_owner(family, given):
            name = "*%s*" % name
        parts.append(name)
    return ", ".join(parts)


# --------------------------------------------------------------------------- #
# jemdoc text
# --------------------------------------------------------------------------- #

def escape(value):
    """Text from the .bib as jemdoc source.

    jemdoc reads *bold*, /italics/, _underline_, +code+, "quotes" and ~spaces~ in
    the text it is given, and passes an HTML entity straight through. A journal
    name holding an ampersand, or a title holding a slash -- "high speed and/or
    long delay" is a real one -- would otherwise turn into markup.

    The slash and the hash are escaped with a backslash rather than an entity:
    an entity is written &#47;, and jemdoc reads the # as the start of a comment
    and drops the rest of the line, which silently removed half a title.
    """
    value = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return value.replace("/", "\\/").replace("#", "\\#")


def wrap(text, indent="  "):
    """One reference, wrapped, with its continuation lines indented for jemdoc.

    jemdoc decides what a line is by its first character, and it strips leading
    spaces, dots and dashes before it does. A continuation line that begins with
    "-" is therefore a new bullet however far it is indented -- one reference
    ended up as two that way, in the middle of a conference name -- so a line
    never begins with any of the characters jemdoc reads as markup.
    """
    lines = textwrap.wrap(text, WIDTH, break_long_words=False,
                          break_on_hyphens=False)
    fixed = [lines[0]] if lines else [""]
    for line in lines[1:]:
        if line[:1] in "-.=+*{":
            fixed[-1] = "%s %s" % (fixed[-1], line[0])
            rest = line[1:].lstrip()
            if rest:
                fixed.append(rest)
        else:
            fixed.append(line)
    return "\n".join(["- " + fixed[0]] + [indent + line for line in fixed[1:]])


def render_reference(fields):
    """One reference line: authors, title, venue, volume, pages, year."""
    pieces = []
    authors = render_authors(fields.get("author", ""))
    if authors:
        pieces.append("%s." % authors)
    if fields.get("title"):
        pieces.append("\u201c%s\u201d" % escape(fields["title"].rstrip(".")))
    venue = escape(fields.get("journal") or fields.get("booktitle") or "")
    tail = []
    if fields.get("volume"):
        tail.append("vol. %s" % escape(fields["volume"]))
    if fields.get("number"):
        tail.append("no. %s" % escape(fields["number"]))
    if fields.get("pages"):
        tail.append("pp. %s" % escape(fields["pages"]))
    year, _month = entry_date(fields)
    if year:
        tail.append(str(year))
    if venue:
        # jemdoc writes -- as an en dash, which is what a page range wants.
        pieces.append("/%s/%s" % (venue, ", " + ", ".join(tail) if tail else ""))
    elif tail:
        pieces.append(", ".join(tail))
    if fields.get("note"):
        pieces.append("(%s)" % escape(fields["note"]))
    text = " ".join(pieces).rstrip()
    return text if text.endswith(".") else text + "."


# --------------------------------------------------------------------------- #
# the page
# --------------------------------------------------------------------------- #

def sort_key(entry):
    """Newest first; entries with no date at all go last."""
    year, month = entry_date(entry[1])
    return (-year, -month)


def section_of(kind, fields):
    national = fields.get("kind", "").strip().lower() == "national"
    for title, types, wants_national in SECTIONS:
        if wants_national == national and kind in types:
            return title
    return None


def group_entries(entries):
    """{section title: [(year, [entries])]}, in page order, newest first."""
    grouped = {}
    for entry in entries:
        title = section_of(entry[0], entry[1])
        if title is not None:
            grouped.setdefault(title, []).append(entry)

    sections = []
    for title, _types, _national in SECTIONS:
        members = sorted(grouped.get(title, []), key=sort_key)
        if not members:
            continue
        years = []
        for entry in members:
            year = entry_date(entry[1])[0] or 0
            if years and years[-1][0] == year:
                years[-1][1].append(entry)
            else:
                years.append((year, [entry]))
        sections.append((title, years))
    return sections


def render_page(entries):
    """The whole .jemdoc source of the page, and how many references it holds."""
    out = [HEADER]
    total = 0
    for title, years in group_entries(entries):
        out.append("== %s\n" % title)
        for _year, members in years:
            total += len(members)
            for entry in members:
                out.append(wrap(render_reference(entry[1])))
            out.append("")
    return "\n".join(out).rstrip() + "\n", total


def read_entries():
    if not os.path.isfile(SOURCE):
        raise SystemExit("no such file: %s" % SOURCE)
    with open(SOURCE, "r", encoding="utf-8") as handle:
        return parse_entries(handle.read())


def main():
    parser = argparse.ArgumentParser(
        description="Write the Publications page from www/data/publications.bib.")
    parser.add_argument("--check", action="store_true",
                        help="write nothing; fail if the page is out of date")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the page instead of writing it")
    arguments = parser.parse_args()

    entries = read_entries()
    page, total = render_page(entries)
    if not total:
        raise SystemExit(
            "no usable entries in %s: refusing to write an empty page" % SOURCE)

    if arguments.check or arguments.dry_run:
        if arguments.dry_run:
            sys.stdout.write(page)
        current = ""
        if os.path.isfile(OUTPUT):
            with open(OUTPUT, "r", encoding="utf-8") as handle:
                current = handle.read()
        if arguments.check and current != page:
            print("www/profile/publications.jemdoc is out of date: "
                  "run python tools/build_publications.py")
            return 1
        if arguments.check:
            print("www/profile/publications.jemdoc is up to date (%d entries)"
                  % total)
        return 0

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(page)
    print("wrote www/profile/publications.jemdoc (%d entries)" % total)
    return 0


if __name__ == "__main__":
    sys.exit(main())